'use strict';
(() => {
  const n=Number(new URLSearchParams(location.search).get('n'));
  if(![2,3,4].includes(n))return;
  const host=document.createElement('section');host.id='literature-lab';host.className='lesson-section literature-lab';
  document.getElementById('warmup').after(host);
  const by=id=>document.getElementById(id);
  const field=(id,label,placeholder='仅在当前页面临时记录；不上传、不评分，刷新后清空。')=>`<label for="${id}">${label}<textarea id="${id}" rows="3" placeholder="${placeholder}"></textarea></label>`;
  const intro=`<p class="eyebrow">同一个任务 · 三次进阶</p><h2>文献检索 Agent 工作台</h2><nav class="lit-path" aria-label="文献任务进阶"><a href="lesson.html?n=2#literature-lab" ${n===2?'aria-current="page"':''}>02 定义任务</a><a href="lesson.html?n=3#literature-lab" ${n===3?'aria-current="page"':''}>03 建立状态</a><a href="lesson.html?n=4#literature-lab" ${n===4?'aria-current="page"':''}>04 探索线索</a></nav><p class="note">课堂模拟，不是联网 Agent。所有材料、页码与图中成本均为虚构教学数据，不能作为真实文献引用。不上传 PDF，不调用大模型；个人输入不发送到后台。</p>`;
  host.innerHTML=intro;
  if(n===2)peas();if(n===3)model();if(n===4)search();
  function peas(){
    host.insertAdjacentHTML('beforeend',`<div class="lit-card"><h3>任务简报</h3><p>研究问题：数字金融与家庭消费有什么关系？助手仅使用给定材料，整理研究问题、数据、方法、发现和局限；每条结论附来源位置，未提供的信息写“未知”。</p><p>输入需求与材料 → 查询和阅读 → 核对原文 → 输出证据表 → 人工复核</p></div><div class="lit-grid">${[['p','P · 用什么标准评价完成得好不好？'],['e','E · 助手在什么环境中工作？'],['a','A · 它可以通过什么接口行动？'],['s','S · 它通过什么接口接收信息？']].map(([id,label])=>field('peas-'+id,label)).join('')}</div><button type="button" class="button secondary" id="peas-check">检查填写完整性</button><p id="peas-feedback" role="status"></p><details class="support"><summary>写完后，对照 PEAS 示例</summary><p>P：相关性、准确性、原文可追溯率、耗时。E：研究需求、给定材料库和使用限制。A：检索接口、打开原文的工具、生成证据表的输出接口。S：问题输入接口，以及接收检索结果与原文内容的接口。真实系统中工具调用是行动，工具返回结果是感知。</p></details><h3>改一个条件：环境判断会变吗？</h3><label for="lit-environment">材料条件</label><select id="lit-environment"><option value="fixed">固定材料，只提供摘要</option><option value="full">固定材料，全文和全部任务状态可见</option><option value="live">外部库，检索期间可能更新</option></select>${field('lit-env-reason','先判断：完全可观察吗？静态吗？说明假设。')}<button id="lit-env-check" class="button secondary" type="button">查看条件解释</button><p id="lit-env-result" role="status"></p><details class="support"><summary>可选：在你已有的 AI 工具中尝试</summary><p>只用本页虚构材料 A 的摘要与模拟原文，要求输出“研究问题｜材料中的发现｜证据位置｜不能确认的信息”。再自己核对原文。没有 AI 账号时手工填写也可以。真实材料须先确认使用和上传权限，不上传隐私或受限全文。</p><p>模拟原文：使用家庭调查数据，报告数字金融指标与消费之间的正相关关系；这一片段不能证明因果关系。来源：虚构材料 A，模拟第 2 页。</p></details>`);
    by('peas-check').onclick=()=>{const missing=['p','e','a','s'].filter(k=>!by('peas-'+k).value.trim());by('peas-feedback').textContent=missing.length?'还未填写：'+missing.join('、').toUpperCase()+'。':'四项已填写。这里只检查非空，不判断内容正确与否；请对照示例解释自己的选择。';};
    by('lit-env-check').onclick=()=>{by('lit-env-result').textContent={fixed:'固定且不随操作变化，可建模为静态；只看到摘要，完成原文核验所需的信息不可见，因此部分可观察。',full:'仅在“所有任务相关状态确实可见”的教学假设下，才可简化为完全可观察。全文可读不等于现实世界的全部事实可知。库不变时可视为静态。',live:'若检索期间有相关材料更新，环境可视为动态；索引覆盖不全或全文受限时通常部分可观察。不能只凭“接入互联网”就断言随机或多智能体。'}[by('lit-environment').value];};
    by('lit-environment').onchange=()=>{by('lit-env-result').textContent='条件已改变，请先更新你的判断。';};
  }
  function model(){
    const core=window.LiteratureCore;let state=core.initial();
    host.insertAdjacentHTML('beforeend',`<p>在这个固定小库里纳入相关且核验通过的材料。先尝试直接“纳入”，再想想它需要哪些前置条件。</p><div class="lit-controls"><label for="lit-paper">当前材料 <select id="lit-paper">${core.papers.map(p=>`<option value="${p.id}">${p.id} · ${p.title}</option>`).join('')}</select></label><label for="lit-target">目标数量 <select id="lit-target"><option>1</option><option selected>2</option><option>3</option></select></label></div><div class="lit-card"><h3 id="lit-title"></h3><p id="lit-abstract"></p><p id="lit-evidence"></p></div><div class="lit-controls"><button id="lit-read" type="button" class="button secondary">读摘要 · 1 分钟</button><button id="lit-verify" type="button" class="button secondary">核验原文 · 2 分钟</button><button id="lit-include" type="button" class="button secondary">纳入 · 1 分钟</button><button id="lit-reset" type="button" class="plain-button">重新开始</button></div><p id="lit-action" role="status" aria-live="polite">先预测每次操作会改变哪个状态字段。</p><div id="lit-state" class="lit-status"></div>${field('lit-state-explain','相同的“当前材料”，为什么可能不是同一个状态？')}<details class="support"><summary>五项定义与状态／节点的区别</summary><p>状态＝（当前材料，已读集合，已核验集合，已纳入集合）。初始：打开 A，各集合为空。动作与转移：切换材料、阅读、核验、纳入，并按前置条件更新集合。目标检验：纳入数量达到设定值，且均相关、核验通过。路径代价：各动作耗时之和。</p><p>累计代价属于搜索节点的路径记录；本例合法动作不依赖剩余预算，因此不必把它重复放入问题状态。若增加“总用时不能超过 6 分钟”的硬约束，就需考虑剩余预算对状态的影响。</p><p>本库仅 A、B 相关，目标为 3 时不可达。这只是给定模型无解，不代表现实中没有第三篇相关文献。相关性是教学预设；真实任务需要明确标准和人工核验。</p></details>`);
    const render=()=>{const p=core.papers.find(p=>p.id===state.current);by('lit-title').textContent=p.id+' · '+p.title;by('lit-abstract').textContent=state.read.includes(p.id)?p.abstract:'摘要尚未读取。';by('lit-evidence').textContent=state.verified.includes(p.id)?p.evidence:'模拟原文尚未核验。';by('lit-state').textContent=`当前=${state.current}；已读={${state.read.join(',')}}；已核验={${state.verified.join(',')}}；已纳入={${state.included.join(',')}}。累计 ${state.cost} 分钟。${core.goal(state,Number(by('lit-target').value))?'目标已达成。':'目标未达成。'}`;};
    ['read','verify','include'].forEach(a=>by('lit-'+a).onclick=()=>{const r=core.act(state,a);state=r.state;by('lit-action').textContent=r.message;render();});
    by('lit-paper').onchange=()=>{const r=core.act(state,'open',by('lit-paper').value);state=r.state;by('lit-action').textContent=r.message;render();};
    by('lit-target').onchange=()=>{by('lit-action').textContent='只改变目标数量，当前状态保留。重新检查完成条件。';render();};
    by('lit-reset').onclick=()=>{state=core.initial();by('lit-paper').value='A';by('lit-action').textContent='已重置材料状态与耗时，目标数量保留。';render();};render();
  }
  function search(){
    const core=window.CourseMap;let trace=[],step=0;
    host.insertAdjacentHTML('beforeend',`<p>本课把任务进一步简化为：从入口 S 沿给定线索找到目标材料 G。A–G 为虚构材料节点，箭头是可沿用的检索／引用线索，数字是教学设定的检查成本。它与第 3 课“收集多篇”的完整状态模型不同。</p><div class="lit-controls"><label for="lit-algorithm">算法 <select id="lit-algorithm"><option value="bfs">BFS · 队列</option><option value="dfs">DFS · 栈</option></select></label><label for="lit-reverse"><input type="checkbox" id="lit-reverse">后继改为较后字母优先</label><label for="lit-blocked"><input type="checkbox" id="lit-blocked">移除 D→E 线索</label><label for="lit-cost">B→E 成本 <input id="lit-cost" type="number" min="1" max="12" value="8"></label></div><p class="lit-explanation">边界表左端先取，节点首次入表即标记已发现；取出 G 时停止。默认字母靠前者优先，DFS 让它先深入。改变条件会重新开始。</p><div id="lit-graph"></div><div class="lit-controls"><label for="lit-predict">预测下一次取出 <select id="lit-predict"><option value="">先选择</option>${Object.keys(core.nodes).map(id=>`<option>${id}</option>`).join('')}</select></label><button id="lit-next" type="button" class="button secondary">验证并执行一步</button><button id="lit-search-reset" type="button" class="plain-button">重置本次实验</button></div><p id="lit-search-feedback" role="status" aria-live="polite"></p><div class="lit-status"><p id="lit-frontier" class="lit-route"></p><p id="lit-taken" class="lit-route"></p><p id="lit-result"></p></div>${field('lit-search-explain','解释：这次选择为什么发生？改一个条件，预测什么会变、什么不变。')}<details class="support"><summary>如何解释结果，而不只报告顺序？</summary><p>BFS 按层数推进；DFS 优先深入一个分支。返回路径只是父节点链，不是所有取出节点连起来的顺序。边权改变不会改变这两种算法的排序依据，但会影响路径成本；下一课 UCS 才按累计成本排序。</p><p>在这个有限图与去重规则下，搜索会终止。不能把这一结论无条件推广到无限深的树搜索。一次 BFS 比 DFS 快，也不能证明它永远更快。</p></details>`);
    const options=()=>({cost:Number(by('lit-cost').value),reverse:by('lit-reverse').checked,blocked:by('lit-blocked').checked});
    const draw=()=>{const t=trace[step],xy=id=>{const [x,y]=core.nodes[id];return [55+x*150,45+y*95];};by('lit-graph').innerHTML=`<svg class="lit-diagram" viewBox="0 0 560 275" role="img" aria-label="有向文献线索图，S 是入口，G 是目标；完整边列表见下方"><defs><marker id="lit-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8" fill="#aaa"/></marker></defs>${core.edges(options()).map(([a,b,c])=>{const [x,y]=xy(a),[u,v]=xy(b),dx=u-x,dy=v-y,len=Math.hypot(dx,dy);return `<line x1="${x+dx/len*24}" y1="${y+dy/len*24}" x2="${u-dx/len*28}" y2="${v-dy/len*28}" stroke="#aaa" stroke-width="2" marker-end="url(#lit-arrow)"/><text x="${(x+u)/2+5}" y="${(y+v)/2-5}">${c}</text>`;}).join('')}${Object.keys(core.nodes).map(id=>{const [x,y]=xy(id);return `<circle cx="${x}" cy="${y}" r="23" fill="white" stroke="#8a194e" stroke-width="2" class="${t.current===id?'lit-active':''}"/><text x="${x}" y="${y+5}" text-anchor="middle">${id}</text>`;}).join('')}</svg><details class="support"><summary>完整线索与成本（文字版）</summary><p>${core.edges(options()).map(([a,b,c])=>`${a} → ${b}：${c}`).join('；')}</p></details>`;};
    const render=()=>{const t=trace[step];by('lit-frontier').textContent='边界表（左端先取）：'+(t.frontier.map(x=>x.id).join(' → ')||'空');by('lit-taken').textContent='已取出：'+(trace.slice(0,step+1).map(x=>x.current).filter(Boolean).join(' → ')||'尚未取出');by('lit-result').textContent=t.done?`返回路径：${t.path.join(' → ')}；成本 ${t.cost}；取出 ${t.taken} 个节点。`:t.message;by('lit-next').disabled=step>=trace.length-1;draw();};
    const reset=()=>{if(!by('lit-cost').checkValidity()){by('lit-search-feedback').textContent='成本须为 1–12 的整数，请修正后继续。';by('lit-next').disabled=true;return;}trace=core.trace(by('lit-algorithm').value,options());step=0;by('lit-predict').value='';by('lit-search-feedback').textContent='先预测，再执行；更改条件后重新计算。';render();};
    ['lit-algorithm','lit-reverse','lit-blocked','lit-cost'].forEach(id=>by(id).onchange=reset);
    by('lit-search-reset').onclick=reset;by('lit-next').onclick=()=>{if(!by('lit-cost').checkValidity()){reset();return;}if(!by('lit-predict').value){by('lit-search-feedback').textContent='先选择你的预测。';return;}const next=trace[step+1];by('lit-search-feedback').textContent=by('lit-predict').value===next.current?'预测正确。解释一下边界表规则。':`这次取出 ${next.current}，请检查${by('lit-algorithm').value==='bfs'?'先进先出':'优先深入'}规则。`;step++;by('lit-predict').value='';render();};reset();
  }
})();
